import Link from "next/link";
import React from "react";
import { Breadcrumb, Table } from "react-bootstrap";
import Meta from "../../components/meta";

export default function IrregularVerbs() {
    return (
        <>
            <Meta title="Irregular Verbs | Vocabulary | EnglishStu | Learn English" />
            <Breadcrumb>
                <Link href="/">
                    <Breadcrumb.Item active>Home</Breadcrumb.Item>
                </Link>
                <Link href="/vocabulary">
                    <Breadcrumb.Item active>Vocabulary</Breadcrumb.Item>
                </Link>
                <Link href="/vocabulary/irregular-verbs">
                    <Breadcrumb.Item active>Irregular Verbs</Breadcrumb.Item>
                </Link>
            </Breadcrumb>
            <h1 className="mb-4">Irregular Verbs List</h1>
            <p>
                This is a list of some irregular verbs in English. Of course,
                there are many others, but these are the more common irregular
                verbs. You can test yourself with these{" "}
                <Link href="/">
                    <a>fun irregular verbs quizzes</a>
                </Link>
                .
            </p>

            <Table responsive striped bordered>
                <thead>
                    <tr>
                        <th>
                            V1
                            <br />
                            Base Form
                        </th>
                        <th>
                            V2
                            <br />
                            Past Simple
                        </th>
                        <th>
                            V3
                            <br />
                            Past Participle
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>awake</td>
                        <td>awoke</td>
                        <td>awoken</td>
                    </tr>
                    <tr>
                        <td>be</td>
                        <td>was, were</td>
                        <td>been</td>
                    </tr>
                    <tr>
                        <td>beat</td>
                        <td>beat</td>
                        <td>beaten</td>
                    </tr>
                    <tr>
                        <td>become</td>
                        <td>became</td>
                        <td>become</td>
                    </tr>
                    <tr>
                        <td>begin</td>
                        <td>began</td>
                        <td>begun</td>
                    </tr>
                    <tr>
                        <td>bend</td>
                        <td>bent</td>
                        <td>bent</td>
                    </tr>
                    <tr>
                        <td>bet</td>
                        <td>bet</td>
                        <td>bet</td>
                    </tr>
                    <tr>
                        <td>bid</td>
                        <td>bid</td>
                        <td>bid</td>
                    </tr>
                    <tr>
                        <td>bite</td>
                        <td>bit</td>
                        <td>bitten</td>
                    </tr>
                    <tr>
                        <td>blow</td>
                        <td>blew</td>
                        <td>blown</td>
                    </tr>
                    <tr>
                        <td>break</td>
                        <td>broke</td>
                        <td>broken</td>
                    </tr>
                    <tr>
                        <td>bring</td>
                        <td>brought</td>
                        <td>brought</td>
                    </tr>
                    <tr>
                        <td>broadcast</td>
                        <td>broadcast</td>
                        <td>broadcast</td>
                    </tr>
                    <tr>
                        <td>build</td>
                        <td>built</td>
                        <td>built</td>
                    </tr>
                    <tr>
                        <td>burn</td>
                        <td>
                            burned <em>or</em> burnt
                        </td>
                        <td>
                            burned <em>or</em> burnt
                        </td>
                    </tr>
                    <tr>
                        <td>buy</td>
                        <td>bought</td>
                        <td>bought</td>
                    </tr>
                    <tr>
                        <td>catch</td>
                        <td>caught</td>
                        <td>caught</td>
                    </tr>
                    <tr>
                        <td>choose</td>
                        <td>chose</td>
                        <td>chosen</td>
                    </tr>
                    <tr>
                        <td>come</td>
                        <td>came</td>
                        <td>come</td>
                    </tr>
                    <tr>
                        <td>cost</td>
                        <td>cost</td>
                        <td>cost</td>
                    </tr>
                    <tr>
                        <td>cut</td>
                        <td>cut</td>
                        <td>cut</td>
                    </tr>
                    <tr>
                        <td>dig</td>
                        <td>dug</td>
                        <td>dug</td>
                    </tr>
                    <tr>
                        <td>do</td>
                        <td>did</td>
                        <td>done</td>
                    </tr>
                    <tr>
                        <td>draw</td>
                        <td>drew</td>
                        <td>drawn</td>
                    </tr>
                    <tr>
                        <td>dream</td>
                        <td>
                            dreamed <em>or</em> dreamt
                        </td>
                        <td>
                            dreamed <em>or</em> dreamt
                        </td>
                    </tr>
                    <tr>
                        <td>drive</td>
                        <td>drove</td>
                        <td>driven</td>
                    </tr>
                    <tr>
                        <td>drink</td>
                        <td>drank</td>
                        <td>drunk</td>
                    </tr>
                    <tr>
                        <td>eat</td>
                        <td>ate</td>
                        <td>eaten</td>
                    </tr>
                    <tr>
                        <td>fall</td>
                        <td>fell</td>
                        <td>fallen</td>
                    </tr>
                    <tr>
                        <td>feel</td>
                        <td>felt</td>
                        <td>felt</td>
                    </tr>
                    <tr>
                        <td>fight</td>
                        <td>fought</td>
                        <td>fought</td>
                    </tr>
                    <tr>
                        <td>find</td>
                        <td>found</td>
                        <td>found</td>
                    </tr>
                    <tr>
                        <td>fly</td>
                        <td>flew</td>
                        <td>flown</td>
                    </tr>
                    <tr>
                        <td>forget</td>
                        <td>forgot</td>
                        <td>forgotten</td>
                    </tr>
                    <tr>
                        <td>forgive</td>
                        <td>forgave</td>
                        <td>forgiven</td>
                    </tr>
                    <tr>
                        <td>freeze</td>
                        <td>froze</td>
                        <td>frozen</td>
                    </tr>
                    <tr>
                        <td>get</td>
                        <td>got</td>
                        <td>
                            got (<em>sometimes</em> gotten)
                        </td>
                    </tr>
                    <tr>
                        <td>give</td>
                        <td>gave</td>
                        <td>given</td>
                    </tr>
                    <tr>
                        <td>go</td>
                        <td>went</td>
                        <td>gone</td>
                    </tr>
                    <tr>
                        <td>grow</td>
                        <td>grew</td>
                        <td>grown</td>
                    </tr>
                    <tr>
                        <td>hang</td>
                        <td>hung</td>
                        <td>hung</td>
                    </tr>
                    <tr>
                        <td>have</td>
                        <td>had</td>
                        <td>had</td>
                    </tr>
                    <tr>
                        <td>hear</td>
                        <td>heard</td>
                        <td>heard</td>
                    </tr>
                    <tr>
                        <td>hide</td>
                        <td>hid</td>
                        <td>hidden</td>
                    </tr>
                    <tr>
                        <td>hit</td>
                        <td>hit</td>
                        <td>hit</td>
                    </tr>
                    <tr>
                        <td>hold</td>
                        <td>held</td>
                        <td>held</td>
                    </tr>
                    <tr>
                        <td>hurt</td>
                        <td>hurt</td>
                        <td>hurt</td>
                    </tr>
                    <tr>
                        <td>keep</td>
                        <td>kept</td>
                        <td>kept</td>
                    </tr>
                    <tr>
                        <td>know</td>
                        <td>knew</td>
                        <td>known</td>
                    </tr>
                    <tr>
                        <td>lay</td>
                        <td>laid</td>
                        <td>laid</td>
                    </tr>
                    <tr>
                        <td>lead</td>
                        <td>led</td>
                        <td>led</td>
                    </tr>
                    <tr>
                        <td>learn</td>
                        <td>
                            learned <em>or</em> learnt
                        </td>
                        <td>
                            learned <em>or</em> learnt
                        </td>
                    </tr>
                    <tr>
                        <td>leave</td>
                        <td>left</td>
                        <td>left</td>
                    </tr>
                    <tr>
                        <td>lend</td>
                        <td>lent</td>
                        <td>lent</td>
                    </tr>
                    <tr>
                        <td>let</td>
                        <td>let</td>
                        <td>let</td>
                    </tr>
                    <tr>
                        <td>lie</td>
                        <td>lay</td>
                        <td>lain</td>
                    </tr>
                    <tr>
                        <td>lose</td>
                        <td>lost</td>
                        <td>lost</td>
                    </tr>
                    <tr>
                        <td>make</td>
                        <td>made</td>
                        <td>made</td>
                    </tr>
                    <tr>
                        <td>mean</td>
                        <td>meant</td>
                        <td>meant</td>
                    </tr>
                    <tr>
                        <td>meet</td>
                        <td>met</td>
                        <td>met</td>
                    </tr>
                    <tr>
                        <td>pay</td>
                        <td>paid</td>
                        <td>paid</td>
                    </tr>
                    <tr>
                        <td>put</td>
                        <td>put</td>
                        <td>put</td>
                    </tr>
                    <tr>
                        <td>read</td>
                        <td>read</td>
                        <td>read</td>
                    </tr>
                    <tr>
                        <td>ride</td>
                        <td>rode</td>
                        <td>ridden</td>
                    </tr>
                    <tr>
                        <td>ring</td>
                        <td>rang</td>
                        <td>rung</td>
                    </tr>
                    <tr>
                        <td>rise</td>
                        <td>rose</td>
                        <td>risen</td>
                    </tr>
                    <tr>
                        <td>run</td>
                        <td>ran</td>
                        <td>run</td>
                    </tr>
                    <tr>
                        <td>say</td>
                        <td>said</td>
                        <td>said</td>
                    </tr>
                    <tr>
                        <td>see</td>
                        <td>saw</td>
                        <td>seen</td>
                    </tr>
                    <tr>
                        <td>sell</td>
                        <td>sold</td>
                        <td>sold</td>
                    </tr>
                    <tr>
                        <td>send</td>
                        <td>sent</td>
                        <td>sent</td>
                    </tr>
                    <tr>
                        <td>show</td>
                        <td>showed</td>
                        <td>
                            showed <em>or</em> shown
                        </td>
                    </tr>
                    <tr>
                        <td>shut</td>
                        <td>shut</td>
                        <td>shut</td>
                    </tr>
                    <tr>
                        <td>sing</td>
                        <td>sang</td>
                        <td>sung</td>
                    </tr>
                    <tr>
                        <td>sink</td>
                        <td>sank</td>
                        <td>sunk</td>
                    </tr>
                    <tr>
                        <td>sit</td>
                        <td>sat</td>
                        <td>sat</td>
                    </tr>
                    <tr>
                        <td>sleep</td>
                        <td>slept</td>
                        <td>slept</td>
                    </tr>
                    <tr>
                        <td>speak</td>
                        <td>spoke</td>
                        <td>spoken</td>
                    </tr>
                    <tr>
                        <td>spend</td>
                        <td>spent</td>
                        <td>spent</td>
                    </tr>
                    <tr>
                        <td>stand</td>
                        <td>stood</td>
                        <td>stood</td>
                    </tr>
                    <tr>
                        <td>stink</td>
                        <td>stank</td>
                        <td>stunk</td>
                    </tr>
                    <tr>
                        <td>swim</td>
                        <td>swam</td>
                        <td>swum</td>
                    </tr>
                    <tr>
                        <td>take</td>
                        <td>took</td>
                        <td>taken</td>
                    </tr>
                    <tr>
                        <td>teach</td>
                        <td>taught</td>
                        <td>taught</td>
                    </tr>
                    <tr>
                        <td>tear</td>
                        <td>tore</td>
                        <td>torn</td>
                    </tr>
                    <tr>
                        <td>tell</td>
                        <td>told</td>
                        <td>told</td>
                    </tr>
                    <tr>
                        <td>think</td>
                        <td>thought</td>
                        <td>thought</td>
                    </tr>
                    <tr>
                        <td>throw</td>
                        <td>threw</td>
                        <td>thrown</td>
                    </tr>
                    <tr>
                        <td>understand</td>
                        <td>understood</td>
                        <td>understood</td>
                    </tr>
                    <tr>
                        <td>wake</td>
                        <td>woke</td>
                        <td>woken</td>
                    </tr>
                    <tr>
                        <td>wear</td>
                        <td>wore</td>
                        <td>worn</td>
                    </tr>
                    <tr>
                        <td>win</td>
                        <td>won</td>
                        <td>won</td>
                    </tr>
                    <tr>
                        <td>write</td>
                        <td>wrote</td>
                        <td>written</td>
                    </tr>
                </tbody>
            </Table>

            <p>
                See also:{" "}
                <Link href="/vocabulary/regular-verbs">
                    <a>regular verbs list</a>
                </Link>
            </p>
            <p>
                Test yourself with these{" "}
                <Link href="/">
                    <a>fun irregular verbs quizzes</a>
                </Link>
            </p>
        </>
    );
}
